<?php

namespace Database\Seeders;

use App\Models\Agent;
use Illuminate\Database\Seeder;

class AgentSeeder extends Seeder
{
    public function run(): void
    {
        // Ported verbatim from the `agentDB` array in the original app.js.
        $agents = [
            'ANAND PERICHERLA', 'HARISH NAGABHAIRU', 'NAVEEN PIRATI', 'POORNIMA ARUMILLI',
            'PRASHANTH REDDY MULA', 'RAGHU JULURI', 'SAI VENKATA RAMESH GOLLU', 'VEENA MARPINA',
            'VIJAY RAMCHETTY', 'VISHNU VARDHAN REDDY BODA', 'C KUMAR KESARWANI', 'DEVI GAJULA',
            'KINNARY THAKKAR', 'HARISH KOPPU', 'PANKAJ BILANDANI', 'RAM CHANDRAPATLA',
            'SRIDEVI KALLAPALLY', 'SRIRAM KESAVAN', 'AKHIL CHAKINAM', 'SUNIL MADDIRALA',
            'KARTHIK PALEM', 'RICHARD ZILKAR', 'K KRISHNA KUMARI', 'VIGNESH SELVARAJ',
            'VENKATESH BONTHU', 'SAILAJA PIRATI', 'MITHILESH RUDRARAJU', 'SATISH YANGALA',
            'DINESH KUMAR KOTHANDAN', 'THANOJ MITTAPALLI', 'DILIP KUMAR MIRIYALA', 'MAHI GADUPUDI',
            'RANADEER REDDY GOGULA', 'AVI SIRIGIRI (Avinash Reddy Sirigiri)', 'DEEKSHA MALIK',
            'GAUTHAM KRISHNA MAMIDI', 'ANJAN JOGIPARTHI (Anjaneswar Jogiparthi)', 'PHANI YARLAGADDA (Phani Ratna Kumar Yarlagadda)',
            'LAXMI JOGIPARTHI (Sreelaxmi Jogiparthi)', 'INDU NADAM', 'YASH BANGALORE ESWARA', 'PRUDHVI MALLULA',
            'PREM BORUGADDA (PREM SWAROOP BORUGADDA)', 'RAJU REDDY NACHHANNAGARI', 'LAKSHMI NADENDLA (Lakshmi Prasanna Nadendla)',
            'AKHIL PERURI', 'MANIKANTA VANAMA', 'VENKAT GUTTIKONDA', 'RAGAV BALASA', 'SUJAN DYAVANAPELLI',
            'JAY PATEL', 'MEGHANA AKKAPALLI', 'LAXMAN NATARAJAN', 'SAURABH CHOUBE', 'SAIKRUSHNA UDARI',
            'SWETHA BONDILI', 'BALJEET SINGH', 'SASI RENIGUNTLA VENKATA', 'VENKATA GUPTA PATNALA',
            'SUBRAT KUMAR', 'KHAZIL MOHAMMED', 'MRUDULA RAYUDU', 'RAMYA MUTYALA', 'ARJUN NIGAM',
            'AMAN MUULTANI', 'NAVEEN VARMA CHALDI', 'FAISAL GALANI (Phil Galani)', 'SHANIZA MOHAMED',
            'MOKTHIKA VISWANADHAPALLI', 'NARASIMHA CHARAN (Charan Uppala)', 'JAGADISH KOTHAPALLI (JAGADISH VARMA KOTHAPALLI)',
            'AKHIL REDDY THOUTREDDY', 'GIRISH TAHILANI', 'JUNAID ABRAR', 'SAHEER SHAIK', 'VENKATA APARNA KANDULA',
            'AAKASH HOODA', 'JAGAN KUMAR SIVARAMAKRISHNAN', 'KRISHNA PARAJULI', 'DIWAKAR WADHERA',
            'YUGANDHAR TAMMINENI', 'SRINI PENUMADU', 'RUSHIKESH TRIVEDI', 'ANKUR KAPUR', 'HARDIK SOLANKI',
            'MEENU GULERYA', 'SACHIN DHARMENDRA PATEL', 'DILAWARJEET MANGAT', 'AAHANA NAYAR', 'FARHAN RASHID',
            'ARAVIND MOHAN', 'DINESH KAUSHIK', 'ANKIT KAPUR', 'MANUDEEP SINGH', 'YADAGIRI MRINAL REDDY KANKARLA',
            'RAKESH CHALLA', 'FAHIM SHAIKH (Ankur Kapur Team)', 'SHAIK ABDULBASITH AL AMOUDI', 'HUMAIRA RAHIM',
            'VIVANYA NAYYAR', 'ANTHONY ARULRAJ', 'SRINIVAS VANGALA (Trade Name: Sri Sri Realty)', 'RISHI VERMA',
            'VARUN MUNJAL', 'SAKTHIVEL PERIASELLAPPAN', 'Ankur Kapur - Team',
        ];

        foreach ($agents as $name) {
            Agent::updateOrCreate(
                ['name' => $name],
                ['is_team' => str_contains($name, '- Team')]
            );
        }
    }
}
