-- The audit trail's own query, and the retention sweep's.
--
-- MEASURED, not guessed. Against a seeded 240,000-row `audit_logs` (8,000 deals × 30 changes):
--
--   SELECT … WHERE domain='desk' ORDER BY created_at DESC, id DESC LIMIT 50
--     before  45.0 ms   Seq Scan + Gather Merge
--     after    4.7 ms   Incremental Sort over this index
--
--   SELECT count(*) … WHERE domain='desk' AND created_at < now() - interval '6 months'
--     before  46.1 ms   Seq Scan
--     after    0.1 ms   Index Only Scan
--
-- Index size 1,688 kB against a 32 MB table — about 5%.
--
-- The second query is the retention sweep's candidate count, which runs on every pass. Without this
-- it is a full scan of the largest table in the schema, on a timer, for ever.
--
-- WHY (domain, created_at DESC) AND NOT `created_at` ALONE. Every read of this table is scoped to an
-- area first — the trail is split into `crm`, `desk` and `common`, and both the listing and the
-- retention sweep filter on it before ordering. Leading with `domain` lets the same index serve the
-- equality and the ordering; leading with the date would not.
--
-- SHARED WITH CRM, AND THAT IS FINE. An index changes no behaviour and no result — the CRM's audit
-- trail runs the identical shape of query with `domain='crm'` and gets the same improvement. The
-- existing single-column `domain` index is left in place: it is what the planner uses for the
-- count-by-category queries that do not order by date, and dropping it is a separate decision that
-- needs its own measurement.
--
-- CREATE INDEX (not CONCURRENTLY) because Prisma runs migrations inside a transaction, and
-- CONCURRENTLY cannot. On a table of this size the lock is brief; if this is ever applied to a very
-- large production table during business hours, build it by hand with CONCURRENTLY first — the
-- IF NOT EXISTS below then makes this migration a no-op.

CREATE INDEX IF NOT EXISTS "audit_logs_domain_created_at_idx"
  ON "audit_logs" ("domain", "created_at" DESC);
